# SPDX-FileCopyrightText: 2023 Sidings Media
# SPDX-License-Identifier: CC0-1.0

title: "Sidings Media"
baseURL: "https://sidingsmedia.com"
languageCode: "en-GB"
theme: "github.com/kdevo/osprey-delight/v5"
tags: ["business", "homepage", "portfolio"]
#canonifyURLS: true
#googleAnalytics: ""
disableKinds: ["taxonomy", "taxonomyTerm"]
enableEmoji: true
pygmentsUseClasses: true

module:
  imports:
  - path: github.com/kdevo/osprey-delight/v5

Params:
  author: "Sidings Media"
  description: "Sidings Media - Open Source Education"
  blogURL: "https://blog.sidingsmedia.com"

  logoBig: "logo/rendered/logo-white-vertical.png"
  logoSmall: "logo/rendered/logo-white.png"
  # background: "background.jpg"
  opengraphImage: "logo/rendered/logo-vertical.png"
  favicon: "logo/rendered/logo.png"

  theme: "custom"
  tagline: "Open source education"
  # mdTagline: "# Sidings Media\n ## Open Source Education{cursor}"
  enforceSinglePage: false
  copyright: true
  credit: false

## Social links in footer:
  Social:
  - type: github
    url: "https://github.com/SidingsMedia/"
  - type: instagram
    url: https://www.instagram.com/sidingsmedia/
  - type: facebook
    url: https://www.facebook.com/sidingsmediaofficial
  - type: twitter
    url: https://twitter.com/SidingsMedia
    
## Additional theme features:
  Feat:
    contactAPI: "https://api.sidingsmedia.com/messaging/contact"
    useStructuredData: true
    useTermynal: true
    googleTagManager: ""
    notifyOnNewThemeVersion: false

    Image:
    Logo:
      resize: "600x"

    Gallery:
      resize: "600x"

    Background:
      resize: "1920x"
      resizeLQIP: "256x"

  # Advanced configuration for lazyimg module (comment out if needed):
  # lazyimg:
  #   resizer: auto
  #   renderer: lqip-webp

  #   # Resizer options:
  #   lqipSize: "120x Gaussian"
  #   maxSize: "1920x"
  #   responsiveSizes: ["320x", "640x", "768x", "1024x", "1366x", "1600x", "1920x"]
  #   resizeOptions: "Lanczos q95"

  #   # Renderer options:
  #   #class: ""
  #   #alt: ""
  #   noscript: true 

Menu:
  Main:
    - name: "About"
      identifier: about 
      url: "/#about"
      weight: 1
    - name: "Projects"
      identifier: gallery
      url: "/#projects"
      weight: 2
    # Commented out until blog.sidingsmedia.com is launched
    # - name: "Blog"
    #   identifier: blog
    #   url: "/#blog"
    #   weight: 3
    # Commented out until we get a backend for the contact form
    - name: "Contact"
      identifier: contact
      url: "/#contact"
      weight: 4
