# SPDX-FileCopyrightText: 2023 Sidings Media
# SPDX-License-Identifier: CC0-1.0

title: "Sidings Media"
baseURL: "https://sidingsmedia.com"
languageCode: "en-GB"
theme: "github.com/kdevo/osprey-delight/v5"
tags: ["business", "homepage", "portfolio"]
#canonifyURLS: true
#googleAnalytics: ""
disableKinds: ["taxonomy", "taxonomyTerm"]
enableEmoji: true
pygmentsUseClasses: true

module:
  imports:
  - path: github.com/kdevo/osprey-delight/v5

Params:
  author: "Sidings Media"
  description: "Sidings Media - Open Source Education"
  blogURL: "https://blog.sidingsmedia.com"

  logoBig: "logo/rendered/logo-white-vertical.png"
  logoSmall: "logo/rendered/logo-white.png"
  # background: "background.jpg"
  opengraphImage: "logo/rendered/logo-vertical.png"
  favicon: "logo/rendered/logo.png"

  theme: "custom"
  tagline: "Open source education"
  # mdTagline: "# Sidings Media\n ## Open Source Education{cursor}"
  enforceSinglePage: false
  copyright: true
  credit: false

  Columns:
  - title: Useful Links
    links:
      - name: Github
        href: "https://github.com/SidingsMedia/"
        icon: github
        external: true
      - name: Docs
        href: https://docs.sidingsmedia.com
        external: true
  - title: Organisation
    links:
      - name: About
        href: "#about"
      - name: Service Status
        href: https://status.sidingsmedia.com
        external: true

  - title: Legal
    links:
      - name: Disclaimer
        href: /legal/disclaimer/
      - name: Terms of Service
        href: /legal/terms/
      - name: Privacy Policy
        href: /legal/privacy/

  - title: Social Media
    links:
      - name: Instagram
        href: "https://www.instagram.com/sidingsmedia/"
        icon: instagram
        external: true
      - name: Facebook
        href: "https://www.facebook.com/sidingsmediaofficial"
        icon: facebook
        external: true
      - name: Twitter
        href: "https://twitter.com/SidingsMedia"
        icon: twitter
        external: true
    
## Additional theme features:
  Feat:
    contactAPI: "https://api.sidingsmedia.com/messaging/contact"
    useStructuredData: true
    useTermynal: true
    googleTagManager: ""
    notifyOnNewThemeVersion: false

    Image:
    Logo:
      resize: "600x"

    Gallery:
      resize: "600x"

    Background:
      resize: "1920x"
      resizeLQIP: "256x"

  # Advanced configuration for lazyimg module (comment out if needed):
  # lazyimg:
  #   resizer: auto
  #   renderer: lqip-webp

  #   # Resizer options:
  #   lqipSize: "120x Gaussian"
  #   maxSize: "1920x"
  #   responsiveSizes: ["320x", "640x", "768x", "1024x", "1366x", "1600x", "1920x"]
  #   resizeOptions: "Lanczos q95"

  #   # Renderer options:
  #   #class: ""
  #   #alt: ""
  #   noscript: true 

Menu:
  Main:
    - name: "About"
      identifier: about 
      url: "/#about"
      weight: 1
    - name: "Projects"
      identifier: gallery
      url: "/#projects"
      weight: 2
    - name: "Blog"
      identifier: blog
      url: "/#blog"
      weight: 3
    # Commented out until we get a backend for the contact form
    - name: "Contact"
      identifier: contact
      url: "/#contact"
      weight: 4
